import type { PurityCheckResult, PurityCheckStatus, PurityReport, PurityTokenAuditSample } from '@/api/admin/adminPlus'
import {
  formatTokenAuditLatencyMS,
  hasTokenAuditSampleData,
  isGeminiTokenAuditProvider,
  multiplierTone,
  normalizeTokenAuditProvider,
  tokenAuditCostTotals,
  tokenAuditDisplayRatio,
  tokenAuditSampleDisplayRatio,
  tokenAuditSampleDisplayRow,
  type TokenAuditTone
} from '@/utils/purityAuditDisplay'

type AppLanguage = 'zh-CN' | 'en'
type PurityCheck = PurityCheckResult
type PurityVerdict = 'official_openai' | 'openai_compatible' | 'official_claude' | 'claude_compatible' | 'partial_compatible' | 'invalid_or_unavailable' | 'unknown' | string

type PdfLabels = {
  title: string
  subtitle: string
  generatedBy: string
  keyOmitted: string
  reportId: string
  provider: string
  apiHost: string
  model: string
  checkedAt: string
  verdict: string
  score: string
  officialScore: string
  compatibilityScore: string
  latency: string
  auditLatency: string
  tokensPerSecond: string
  inputTokens: string
  outputTokens: string
  evidence: string
  requestedModel: string
  responseModel: string
  responseModelSource: string
  modelIdentity: string
  wrapperSignals: string
  noWrapperSignals: string
  signalCount: string
  identityReason: string
  suspectedUpstreamVendor: string
  summary: string
  validations: string
  tokenAudit: string
  tokenAuditSkipped: string
  officialBaseline: string
  actualCost: string
  usageRatio: string
  billingMultiplier: string
  cacheHitRate: string
  probeDetails: string
  scoreDetail: string
  status: string
  message: string
  round: string
  input: string
  output: string
  cacheCreate: string
  cacheRead: string
  actual: string
  page: string
}

type PdfImage = {
  data: Uint8Array
  width: number
  height: number
}

type ReportPage = {
  canvas: HTMLCanvasElement
  ctx: CanvasRenderingContext2D
  y: number
}

type DrawState = {
  labels: PdfLabels
  language: AppLanguage
  pages: ReportPage[]
  current: ReportPage
}

type TextStyle = {
  size: number
  weight?: number
  color?: string
  lineHeight?: number
  align?: CanvasTextAlign
}

const pageWidth = 1240
const pageHeight = 1754
const marginX = 72
const contentWidth = pageWidth - marginX * 2
const headerBottom = 156
const contentBottom = pageHeight - 104
const fontStack = 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif'

const zhLabels: PdfLabels = {
  title: 'AI API 纯度检测报告',
  subtitle: '黑盒探针 · 协议能力 · Token 审计',
  generatedBy: '由 proxyai.best 生成',
  keyOmitted: 'API Key 已从报告中排除',
  reportId: '报告 ID',
  provider: '接口类型',
  apiHost: 'API Host',
  model: '目标模型',
  checkedAt: '检测时间',
  verdict: '判定',
  score: '总分',
  officialScore: '官方度',
  compatibilityScore: '兼容度',
  latency: '延迟',
  auditLatency: '耗时',
  tokensPerSecond: 'Tokens/秒',
  inputTokens: '输入 Tokens',
  outputTokens: '输出 Tokens',
  evidence: '模型与包装证据',
  requestedModel: '请求模型',
  responseModel: '响应模型',
  responseModelSource: '响应模型来源',
  modelIdentity: '模型身份',
  wrapperSignals: '包装信号',
  noWrapperSignals: '未发现',
  signalCount: '{count} 个',
  identityReason: '身份原因',
  suspectedUpstreamVendor: '疑似上游厂商',
  summary: '检测摘要',
  validations: '验证项',
  tokenAudit: 'Token 用量审计',
  tokenAuditSkipped: 'Token 用量审计未执行或未返回。',
  officialBaseline: '官方基线',
  actualCost: 'Usage 估算',
  usageRatio: 'Usage 比值',
  billingMultiplier: '平台计费倍率',
  cacheHitRate: '缓存命中率',
  probeDetails: '后端探针明细',
  scoreDetail: '得分',
  status: '状态',
  message: '说明',
  round: '轮次',
  input: '输入',
  output: '输出',
  cacheCreate: '缓存创建',
  cacheRead: '缓存读取',
  actual: '实际',
  page: '页'
}

const enLabels: PdfLabels = {
  title: 'AI API Purity Report',
  subtitle: 'Black-box probes · Protocol capability · Token audit',
  generatedBy: 'Generated by proxyai.best',
  keyOmitted: 'API key is intentionally omitted',
  reportId: 'Report ID',
  provider: 'Provider',
  apiHost: 'API Host',
  model: 'Target model',
  checkedAt: 'Checked at',
  verdict: 'Verdict',
  score: 'Score',
  officialScore: 'Official score',
  compatibilityScore: 'Compatibility',
  latency: 'Latency',
  auditLatency: 'Time',
  tokensPerSecond: 'Tokens/sec',
  inputTokens: 'Input tokens',
  outputTokens: 'Output tokens',
  evidence: 'Model and wrapper evidence',
  requestedModel: 'Requested model',
  responseModel: 'Response model',
  responseModelSource: 'Response model source',
  modelIdentity: 'Model identity',
  wrapperSignals: 'Wrapper signals',
  noWrapperSignals: 'None',
  signalCount: '{count} signal(s)',
  identityReason: 'Identity reason',
  suspectedUpstreamVendor: 'Suspected upstream vendor',
  summary: 'Summary',
  validations: 'Validations',
  tokenAudit: 'Token usage audit',
  tokenAuditSkipped: 'Token usage audit was not executed or not returned.',
  officialBaseline: 'Official baseline',
  actualCost: 'Usage estimate',
  usageRatio: 'Usage ratio',
  billingMultiplier: 'Platform billing ratio',
  cacheHitRate: 'Cache hit rate',
  probeDetails: 'Backend probe details',
  scoreDetail: 'Score',
  status: 'Status',
  message: 'Message',
  round: 'Round',
  input: 'Input',
  output: 'Output',
  cacheCreate: 'Cache create',
  cacheRead: 'Cache read',
  actual: 'Actual',
  page: 'Page'
}

export async function downloadPurityReportPDF(report: PurityReport, options: { language?: AppLanguage } = {}): Promise<void> {
  const language = options.language || 'zh-CN'
  const pages = renderPurityReportPages(report, language)
  const images = pages.map((page) => canvasToJpeg(page.canvas))
  const pdf = buildImagePDF(images)
  downloadBlob(pdf, `proxyai-purity-${safeFilePart(report.provider)}-${safeFilePart(report.report_id || String(Date.now()))}.pdf`)
}

function renderPurityReportPages(report: PurityReport, language: AppLanguage): ReportPage[] {
  const labels = language === 'zh-CN' ? zhLabels : enLabels
  const firstPage = createPage(labels)
  const state: DrawState = { labels, language, pages: [firstPage], current: firstPage }

  drawOverview(state, report)
  drawEvidence(state, report)
  drawValidations(state, report)
  drawTokenAudit(state, report)
  drawProbeDetails(state, report.checks)
  finalizePages(state)

  return state.pages
}

function drawOverview(state: DrawState, report: PurityReport) {
  ensureSpace(state, 560)
  const y = state.current.y
  drawPanel(state.current.ctx, marginX, y, contentWidth, 528, '#0d0c18', '#2d2a43', 34)

  const ctx = state.current.ctx
  const scoreX = marginX + 176
  const scoreY = y + 198
  drawScoreRing(ctx, scoreX, scoreY, report.score)

  drawText(ctx, `${providerLabel(report.provider)} · ${report.model_id}`, marginX + 364, y + 76, { size: 30, weight: 800, color: '#ffffff' })
  drawPill(ctx, marginX + 364, y + 106, verdictLabel(report.verdict, state.language), verdictTone(report.verdict), 26)

  const metaX = marginX + 364
  const metaY = y + 172
  const metaItems = [
    [state.labels.reportId, report.report_id || '-'],
    [state.labels.provider, providerLabel(report.provider)],
    [state.labels.apiHost, report.api_base_host || '-'],
    [state.labels.model, report.response_model || report.expected_model || report.model_id || '-'],
    [state.labels.checkedAt, formatDate(report.checked_at, state.language)]
  ]
  drawKeyValueList(ctx, metaItems, metaX, metaY, contentWidth - 424)

  const summaryTop = y + 358
  drawText(ctx, state.labels.summary, marginX + 36, summaryTop, { size: 22, weight: 800, color: '#ffffff' })
  drawWrappedText(ctx, report.summary || '-', marginX + 36, summaryTop + 34, contentWidth - 72, { size: 20, weight: 500, color: '#c6c8dc', lineHeight: 1.48 })

  state.current.y = y + 560

  const metrics = [
    { label: state.labels.score, value: `${clamp(report.score, 0, 100)}%` },
    { label: state.labels.officialScore, value: `${clamp(report.official_score, 0, 100)}%` },
    { label: state.labels.compatibilityScore, value: `${clamp(report.compatibility_score, 0, 100)}%` },
    { label: state.labels.latency, value: formatMS(report.metrics.latency_ms || report.metrics.responses_latency_ms || report.metrics.messages_latency_ms || 0) },
    { label: state.labels.tokensPerSecond, value: report.metrics.tokens_per_second ? report.metrics.tokens_per_second.toFixed(1) : '0.0' },
    { label: state.labels.inputTokens, value: formatInteger(report.metrics.usage?.input_tokens || report.token_audit?.input_tokens || 0) },
    { label: state.labels.outputTokens, value: formatInteger(report.metrics.usage?.output_tokens || report.token_audit?.output_tokens || 0) }
  ]
  drawMetricGrid(state, metrics)
}

function drawEvidence(state: DrawState, report: PurityReport) {
  const identity = report.model_identity || report.modelIdentity
  const wrapperSignals = wrapperSignalsForReport(report)
  const suspectedVendor = suspectedUpstreamVendor(identity)
  drawSectionTitle(state, state.labels.evidence)
  drawMetricGrid(state, [
    { label: state.labels.requestedModel, value: report.expected_model || report.expectedModel || report.model_id || '-' },
    { label: state.labels.responseModel, value: report.response_model || report.responseModel || '-' },
    { label: state.labels.responseModelSource, value: report.response_model_source || report.responseModelSource || '-' },
    { label: state.labels.modelIdentity, value: identity ? statusLabel(identity.status, state.language) : '-' },
    {
      label: state.labels.wrapperSignals,
      value: wrapperSignals.length ? state.labels.signalCount.replace('{count}', String(wrapperSignals.length)) : state.labels.noWrapperSignals
    }
  ])

  const details = [
    identity?.reason ? `${state.labels.identityReason}: ${identity.reason}` : '',
    suspectedVendor ? `${state.labels.suspectedUpstreamVendor}: ${suspectedVendor}` : '',
    wrapperSignals.length ? `${state.labels.wrapperSignals}: ${wrapperSignals.join(', ')}` : ''
  ].filter(Boolean).join(' · ')
  if (details) {
    drawInfoBox(state, details, '#111827', '#263247', '#c6c8dc')
  }
}

function suspectedUpstreamVendor(identity?: PurityReport['model_identity'] | PurityReport['modelIdentity']): string {
  const value = identity?.evidence?.suspected_upstream_vendor
  return typeof value === 'string' ? value : ''
}

function drawValidations(state: DrawState, report: PurityReport) {
  const rows = report.validations.length ? report.validations : validationFallback(report)
  drawSectionTitle(state, state.labels.validations)
  for (const validation of rows) {
    const rightText = 'score' in validation ? scoreText(validation.score, validation.max_score, state.labels) : ''
    drawStatusRow(state, validation.name, validation.status, validation.message || statusLabel(validation.status, state.language), rightText)
  }
}

function drawTokenAudit(state: DrawState, report: PurityReport) {
  const audit = report.token_audit
  const provider = normalizeTokenAuditProvider(report.provider)
  drawSectionTitle(state, state.labels.tokenAudit)
  if (!audit) {
    drawInfoBox(state, state.labels.tokenAuditSkipped, '#17121a', '#5b461f', '#c5a85b')
    return
  }

  const totals = tokenAuditCostTotals(audit)
  const billingMultiplier = audit.billing_multiplier ?? audit.billingMultiplier
  const hasBillingMultiplier = typeof billingMultiplier === 'number' && Number.isFinite(billingMultiplier)
  const auditMetrics = [
    { label: state.labels.officialBaseline, value: formatUSD(totals.officialBaselineUSD) },
    { label: state.labels.actualCost, value: formatUSD(totals.actualCostUSD) },
    hasBillingMultiplier
      ? { label: state.labels.billingMultiplier, value: formatMultiplier(billingMultiplier) }
      : { label: state.labels.billingMultiplier, value: '-' },
    { label: state.labels.usageRatio, value: formatMultiplier(tokenAuditDisplayRatio(audit)) },
    { label: state.labels.cacheHitRate, value: formatPercent(audit.cacheHitRate ?? audit.cache_hit_rate) },
    { label: 'Samples', value: String(audit.sample_count || audit.samples.length || 0) },
    { label: 'Price', value: audit.price_source || '-' }
  ]
  drawMetricGrid(state, auditMetrics)

  const tone = audit.status === 'fail' ? 'bad' : audit.status === 'warn' ? multiplierTone(tokenAuditDisplayRatio(audit)) : multiplierTone(tokenAuditDisplayRatio(audit))
  drawInfoBox(state, audit.summary || '-', auditInfoFill(tone), auditInfoStroke(tone), pdfAuditToneColor(tone))

  const rawSamples = (audit.rows?.length ? audit.rows : audit.samples).slice(0, 11)
  const chartSamples = rawSamples.filter(hasTokenAuditSampleData)
  const diagnosticSamples = rawSamples.length - chartSamples.length
  if (diagnosticSamples > 0) {
    const text = state.language === 'zh-CN'
      ? `${diagnosticSamples} 轮只返回失败诊断，明细表保留 0 值；请结合 status_code/error_class/error_message 复核。`
      : `${diagnosticSamples} round(s) returned diagnostics only; the table keeps zero values and should be reviewed with status_code/error_class/error_message.`
    drawInfoBox(state, text, '#17121a', '#5b461f', '#ffc857')
  }
  if (chartSamples.length) {
    drawAuditChart(state, chartSamples)
  }
  if (isGeminiTokenAuditProvider(provider) && rawSamples.some((sample) => {
    const row = tokenAuditSampleDisplayRow(sample, provider)
    return row.cacheCreation.available === false || row.cacheRead.available === false
  })) {
    const text = state.language === 'zh-CN'
      ? 'Gemini 未返回或未命中的缓存字段以 0 展示；缓存创建字段不可确认，缓存读取 0 表示本轮未观察到命中。'
      : 'Gemini cache fields that are missing or not hit are shown as 0; cache creation is unconfirmed, while cache read 0 means no hit was observed in that round.'
    drawInfoBox(state, text, '#17121a', '#5b461f', '#ffc857')
  }
  if (rawSamples.length) {
    drawAuditTable(state, rawSamples, provider, hasBillingMultiplier ? billingMultiplier : undefined)
  } else {
    drawInfoBox(state, state.labels.tokenAuditSkipped, '#17121a', '#5b461f', '#c5a85b')
  }
}

function drawProbeDetails(state: DrawState, checks: PurityCheck[]) {
  drawSectionTitle(state, state.labels.probeDetails)
  if (!checks.length) {
    drawInfoBox(state, '-', '#12111f', '#242239', '#aaa8bc')
    return
  }
  for (const check of checks) {
    drawStatusRow(state, check.name, check.status, check.message || '-', scoreText(check.score, check.max_score, state.labels))
  }
}

function drawMetricGrid(state: DrawState, metrics: Array<{ label: string; value: string }>) {
  const columns = 3
  const gap = 18
  const cardWidth = (contentWidth - gap * (columns - 1)) / columns
  const cardHeight = 110
  for (let index = 0; index < metrics.length; index += columns) {
    ensureSpace(state, cardHeight + 18)
    const y = state.current.y
    metrics.slice(index, index + columns).forEach((item, offset) => {
      const x = marginX + offset * (cardWidth + gap)
      drawPanel(state.current.ctx, x, y, cardWidth, cardHeight, '#151426', '#242239', 20)
      drawText(state.current.ctx, item.label, x + 24, y + 36, { size: 18, weight: 700, color: '#8e8ca3' })
      drawText(state.current.ctx, item.value, x + 24, y + 78, { size: 28, weight: 800, color: '#78b8ff' })
    })
    state.current.y = y + cardHeight + 18
  }
}

function drawSectionTitle(state: DrawState, title: string) {
  ensureSpace(state, 74)
  state.current.y += 18
  drawText(state.current.ctx, title, marginX, state.current.y + 34, { size: 28, weight: 800, color: '#ffffff' })
  state.current.y += 70
}

function drawStatusRow(state: DrawState, title: string, status: PurityCheckStatus, message: string, rightText: string) {
  const maxMessageWidth = contentWidth - 270
  const messageLines = wrapLines(state.current.ctx, message, maxMessageWidth, 18, 500)
  const height = Math.max(104, 74 + messageLines.length * 25)
  ensureSpace(state, height + 12)

  const ctx = state.current.ctx
  const y = state.current.y
  drawPanel(ctx, marginX, y, contentWidth, height, '#12111f', '#242239', 18)
  drawStatusDot(ctx, marginX + 30, y + 36, status)
  drawText(ctx, title, marginX + 60, y + 42, { size: 22, weight: 800, color: '#ffffff' })
  drawText(ctx, statusLabel(status, state.language), pageWidth - marginX - 30, y + 42, { size: 20, weight: 800, color: statusColor(status), align: 'right' })
  drawWrappedText(ctx, message, marginX + 60, y + 74, maxMessageWidth, { size: 18, weight: 500, color: '#aaa8bc', lineHeight: 1.38 })
  drawText(ctx, rightText, pageWidth - marginX - 30, y + height - 26, { size: 18, weight: 700, color: '#8e8ca3', align: 'right' })
  state.current.y = y + height + 12
}

function drawInfoBox(state: DrawState, text: string, fill: string, stroke: string, color: string) {
  const lines = wrapLines(state.current.ctx, text, contentWidth - 48, 20, 600)
  const height = Math.max(92, 46 + lines.length * 30)
  ensureSpace(state, height + 16)
  const y = state.current.y
  drawPanel(state.current.ctx, marginX, y, contentWidth, height, fill, stroke, 18)
  drawWrappedText(state.current.ctx, text, marginX + 24, y + 34, contentWidth - 48, { size: 20, weight: 600, color, lineHeight: 1.45 })
  state.current.y = y + height + 16
}

function drawAuditChart(state: DrawState, samples: PurityTokenAuditSample[]) {
  ensureSpace(state, 308)
  const ctx = state.current.ctx
  const y = state.current.y
  drawPanel(ctx, marginX, y, contentWidth, 284, '#0b0a16', '#2b293d', 22)

  const maxCost = Math.max(...samples.map((sample) => Math.max(sample.official_baseline_usd || sample.baseline_cost || 0, sample.actual_cost_usd || sample.cost || 0)), 0.000001)
  const chartLeft = marginX + 54
  const chartBottom = y + 212
  const slot = (contentWidth - 108) / samples.length

  samples.forEach((sample, index) => {
    const officialCost = sample.official_baseline_usd || sample.baseline_cost || 0
    const actualCost = sample.actual_cost_usd || sample.cost || 0
    const officialHeight = clamp((officialCost / maxCost) * 140, 8, 140)
    const actualHeight = clamp((actualCost / maxCost) * 140, 8, 140)
    const ratio = tokenAuditSampleDisplayRatio(sample)
    const tone = multiplierTone(ratio)
    const x = chartLeft + index * slot + slot / 2 - 22
    drawRoundRect(ctx, x, chartBottom - officialHeight, 16, officialHeight, 5)
    ctx.fillStyle = '#484755'
    ctx.fill()
    drawRoundRect(ctx, x + 24, chartBottom - actualHeight, 16, actualHeight, 5)
    ctx.fillStyle = pdfAuditToneColor(tone)
    ctx.fill()
    drawText(ctx, `R${sampleRound(sample, index)}`, x + 20, chartBottom + 28, { size: 16, weight: 700, color: '#8e8ca3', align: 'center' })
    drawText(ctx, formatMultiplier(ratio), x + 20, chartBottom + 56, { size: 18, weight: 800, color: pdfAuditToneColor(tone), align: 'center' })
  })

  drawText(ctx, state.labels.officialBaseline, pageWidth - marginX - 270, y + 42, { size: 18, weight: 700, color: '#8e8ca3' })
  ctx.fillStyle = '#484755'
  ctx.fillRect(pageWidth - marginX - 306, y + 28, 22, 22)
  drawText(ctx, state.labels.actualCost, pageWidth - marginX - 132, y + 42, { size: 18, weight: 700, color: '#8e8ca3' })
  ctx.fillStyle = '#35d39b'
  ctx.fillRect(pageWidth - marginX - 168, y + 28, 22, 22)

  state.current.y = y + 308
}

function drawAuditTable(state: DrawState, samples: PurityTokenAuditSample[], provider: string, billingMultiplier?: number) {
  const rowHeight = 46
  const tableHeaderHeight = 54
  ensureSpace(state, tableHeaderHeight + rowHeight + 24)
  const ctx = state.current.ctx
  const columns = [
    { label: state.labels.round, x: marginX + 24, align: 'left' as CanvasTextAlign },
    { label: state.labels.auditLatency, x: marginX + 150, align: 'right' as CanvasTextAlign },
    { label: state.labels.input, x: marginX + 285, align: 'right' as CanvasTextAlign },
    { label: state.labels.output, x: marginX + 420, align: 'right' as CanvasTextAlign },
    { label: state.labels.cacheCreate, x: marginX + 585, align: 'right' as CanvasTextAlign },
    { label: state.labels.cacheRead, x: marginX + 740, align: 'right' as CanvasTextAlign },
    { label: state.labels.actual, x: marginX + 930, align: 'right' as CanvasTextAlign },
    { label: billingMultiplier !== undefined ? state.labels.billingMultiplier : state.labels.usageRatio, x: marginX + contentWidth - 24, align: 'right' as CanvasTextAlign }
  ]

  ensureSpace(state, tableHeaderHeight + rowHeight * samples.length + 24)
  let y = state.current.y
  drawPanel(ctx, marginX, y, contentWidth, tableHeaderHeight + rowHeight * samples.length, '#0d0c18', '#242239', 18)
  columns.forEach((column) => drawText(ctx, column.label, column.x, y + 34, { size: 16, weight: 800, color: '#8e8ca3', align: column.align }))
  ctx.strokeStyle = '#242239'
  ctx.lineWidth = 2
  ctx.beginPath()
  ctx.moveTo(marginX + 18, y + tableHeaderHeight)
  ctx.lineTo(marginX + contentWidth - 18, y + tableHeaderHeight)
  ctx.stroke()

  y += tableHeaderHeight
  for (const [index, sample] of samples.entries()) {
    if (y + rowHeight > contentBottom) {
      state.current.y = y + 18
      state.current = addPage(state)
      y = state.current.y
      drawPanel(state.current.ctx, marginX, y, contentWidth, tableHeaderHeight + rowHeight * (samples.length - index), '#0d0c18', '#242239', 18)
      y += tableHeaderHeight
    }
    const row = tokenAuditSampleDisplayRow(sample, provider)
    drawText(state.current.ctx, `R${sampleRound(sample, index)}`, columns[0].x, y + 30, { size: 17, weight: 700, color: '#d9d7e7', align: columns[0].align })
    drawText(state.current.ctx, formatTokenAuditLatencyMS(row.latency.value), columns[1].x, y + 30, { size: 17, weight: 800, color: pdfAuditToneColor(row.latency.tone), align: columns[1].align })
    drawText(state.current.ctx, formatInteger(row.input.value), columns[2].x, y + 30, { size: 17, weight: 700, color: pdfAuditToneColor(row.input.tone), align: columns[2].align })
    drawText(state.current.ctx, formatInteger(row.output.value), columns[3].x, y + 30, { size: 17, weight: 700, color: pdfAuditToneColor(row.output.tone), align: columns[3].align })
    drawText(state.current.ctx, row.cacheCreation.display, columns[4].x, y + 30, { size: 17, weight: 700, color: pdfAuditToneColor(row.cacheCreation.tone), align: columns[4].align })
    drawText(state.current.ctx, row.cacheRead.display, columns[5].x, y + 30, { size: 17, weight: 700, color: pdfAuditToneColor(row.cacheRead.tone), align: columns[5].align })
    drawText(state.current.ctx, formatUSD(row.cost.value), columns[6].x, y + 30, { size: 17, weight: 700, color: pdfAuditToneColor(row.cost.tone), align: columns[6].align })
    const ratioDisplay = billingMultiplier !== undefined ? formatMultiplier(billingMultiplier) : row.multiplier.display
    const ratioTone = billingMultiplier !== undefined ? 'good' : row.multiplier.tone
    drawText(state.current.ctx, ratioDisplay, columns[7].x, y + 30, { size: 17, weight: 800, color: pdfAuditToneColor(ratioTone), align: columns[7].align })
    y += rowHeight
  }
  state.current.y = y + 24
}

function createPage(labels: PdfLabels): ReportPage {
  const canvas = document.createElement('canvas')
  canvas.width = pageWidth
  canvas.height = pageHeight
  const ctx = canvas.getContext('2d')
  if (!ctx) {
    throw new Error('Canvas is not available')
  }
  drawPageBackground(ctx)
  drawPageHeader(ctx, labels)
  return { canvas, ctx, y: headerBottom + 34 }
}

function addPage(state: DrawState): ReportPage {
  const page = createPage(state.labels)
  state.pages.push(page)
  state.current = page
  return page
}

function ensureSpace(state: DrawState, height: number) {
  if (state.current.y + height <= contentBottom) {
    return
  }
  addPage(state)
}

function finalizePages(state: DrawState) {
  state.pages.forEach((page, index) => {
    const ctx = page.ctx
    ctx.fillStyle = '#080716'
    ctx.fillRect(0, pageHeight - 82, pageWidth, 82)
    ctx.strokeStyle = '#242239'
    ctx.lineWidth = 2
    ctx.beginPath()
    ctx.moveTo(marginX, pageHeight - 82)
    ctx.lineTo(pageWidth - marginX, pageHeight - 82)
    ctx.stroke()
    drawText(ctx, `${state.labels.generatedBy} · ${state.labels.keyOmitted}`, marginX, pageHeight - 38, { size: 17, weight: 600, color: '#8e8ca3' })
    drawText(ctx, `${state.labels.page} ${index + 1}/${state.pages.length}`, pageWidth - marginX, pageHeight - 38, { size: 17, weight: 700, color: '#8e8ca3', align: 'right' })
  })
}

function drawPageBackground(ctx: CanvasRenderingContext2D) {
  const gradient = ctx.createLinearGradient(0, 0, 0, pageHeight)
  gradient.addColorStop(0, '#04040d')
  gradient.addColorStop(0.48, '#080716')
  gradient.addColorStop(1, '#262257')
  ctx.fillStyle = gradient
  ctx.fillRect(0, 0, pageWidth, pageHeight)

  const glow = ctx.createRadialGradient(pageWidth * 0.5, pageHeight * 1.03, 20, pageWidth * 0.5, pageHeight * 1.03, 620)
  glow.addColorStop(0, 'rgba(104,168,255,0.28)')
  glow.addColorStop(1, 'rgba(104,168,255,0)')
  ctx.fillStyle = glow
  ctx.fillRect(0, 0, pageWidth, pageHeight)
}

function drawPageHeader(ctx: CanvasRenderingContext2D, labels: PdfLabels) {
  drawText(ctx, 'proxyai.best', marginX, 72, { size: 30, weight: 900, color: '#ffffff' })
  drawText(ctx, labels.title, marginX, 112, { size: 26, weight: 800, color: '#c6c8dc' })
  drawText(ctx, labels.subtitle, pageWidth - marginX, 94, { size: 18, weight: 700, color: '#8e8ca3', align: 'right' })
  ctx.strokeStyle = '#2d2a43'
  ctx.lineWidth = 2
  ctx.beginPath()
  ctx.moveTo(marginX, 136)
  ctx.lineTo(pageWidth - marginX, 136)
  ctx.stroke()
}

function drawScoreRing(ctx: CanvasRenderingContext2D, centerX: number, centerY: number, score: number) {
  const normalized = clamp(score, 0, 100)
  const radius = 118
  ctx.lineWidth = 30
  ctx.lineCap = 'round'
  ctx.strokeStyle = '#242239'
  ctx.beginPath()
  ctx.arc(centerX, centerY, radius, 0, Math.PI * 2)
  ctx.stroke()
  ctx.strokeStyle = normalized >= 80 ? '#68a8ff' : normalized >= 55 ? '#e4b449' : '#ff746c'
  ctx.beginPath()
  ctx.arc(centerX, centerY, radius, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2 * (normalized / 100))
  ctx.stroke()
  drawText(ctx, `${normalized}%`, centerX, centerY + 18, { size: 54, weight: 900, color: '#ffffff', align: 'center' })
}

function drawKeyValueList(ctx: CanvasRenderingContext2D, items: string[][], x: number, y: number, width: number) {
  items.forEach(([label, value], index) => {
    const rowY = y + index * 34
    drawText(ctx, label, x, rowY, { size: 17, weight: 700, color: '#8e8ca3' })
    drawText(ctx, ellipsize(ctx, value, width - 170, 18, 700), x + 170, rowY, { size: 18, weight: 700, color: '#d9d8e6' })
  })
}

function drawPill(ctx: CanvasRenderingContext2D, x: number, y: number, text: string, color: string, height: number) {
  setFont(ctx, { size: 16, weight: 800 })
  const width = Math.min(520, Math.max(128, ctx.measureText(text).width + 34))
  drawPanel(ctx, x, y, width, height, color, color, 13)
  drawText(ctx, text, x + width / 2, y + 19, { size: 16, weight: 800, color: '#071018', align: 'center' })
}

function drawStatusDot(ctx: CanvasRenderingContext2D, x: number, y: number, status: PurityCheckStatus) {
  ctx.fillStyle = statusColor(status)
  ctx.beginPath()
  ctx.arc(x, y, 11, 0, Math.PI * 2)
  ctx.fill()
}

function drawPanel(ctx: CanvasRenderingContext2D, x: number, y: number, width: number, height: number, fill: string, stroke: string, radius: number) {
  drawRoundRect(ctx, x, y, width, height, radius)
  ctx.fillStyle = fill
  ctx.fill()
  ctx.strokeStyle = stroke
  ctx.lineWidth = 2
  ctx.stroke()
}

function drawRoundRect(ctx: CanvasRenderingContext2D, x: number, y: number, width: number, height: number, radius: number) {
  const r = Math.min(radius, width / 2, height / 2)
  ctx.beginPath()
  ctx.moveTo(x + r, y)
  ctx.lineTo(x + width - r, y)
  ctx.quadraticCurveTo(x + width, y, x + width, y + r)
  ctx.lineTo(x + width, y + height - r)
  ctx.quadraticCurveTo(x + width, y + height, x + width - r, y + height)
  ctx.lineTo(x + r, y + height)
  ctx.quadraticCurveTo(x, y + height, x, y + height - r)
  ctx.lineTo(x, y + r)
  ctx.quadraticCurveTo(x, y, x + r, y)
  ctx.closePath()
}

function drawText(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, style: TextStyle) {
  setFont(ctx, style)
  ctx.fillStyle = style.color || '#ffffff'
  ctx.textAlign = style.align || 'left'
  ctx.textBaseline = 'alphabetic'
  ctx.fillText(text, x, y)
  ctx.textAlign = 'left'
}

function drawWrappedText(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, width: number, style: TextStyle): number {
  const lineHeight = Math.round(style.size * (style.lineHeight || 1.35))
  const lines = wrapLines(ctx, text, width, style.size, style.weight || 400)
  lines.forEach((line, index) => drawText(ctx, line, x, y + index * lineHeight, style))
  return lines.length * lineHeight
}

function wrapLines(ctx: CanvasRenderingContext2D, text: string, width: number, size: number, weight: number): string[] {
  setFont(ctx, { size, weight })
  const tokens = tokenizeText(text)
  const lines: string[] = []
  let line = ''
  for (const token of tokens) {
    const next = line + token
    if (line && ctx.measureText(next).width > width) {
      lines.push(line.trimEnd())
      line = token.trimStart()
    } else {
      line = next
    }
  }
  if (line.trim()) {
    lines.push(line.trimEnd())
  }
  return lines.length ? lines : ['']
}

function tokenizeText(text: string): string[] {
  return String(text || '').match(/[\u3040-\u30ff\u3400-\u9fff\ud840-\ud87f][\udc00-\udfff]?|[^\s\u3040-\u30ff\u3400-\u9fff]+|\s+/g) || ['']
}

function setFont(ctx: CanvasRenderingContext2D, style: Pick<TextStyle, 'size' | 'weight'>) {
  ctx.font = `${style.weight || 400} ${style.size}px ${fontStack}`
}

function ellipsize(ctx: CanvasRenderingContext2D, text: string, width: number, size: number, weight: number): string {
  setFont(ctx, { size, weight })
  if (ctx.measureText(text).width <= width) {
    return text
  }
  let left = 0
  let right = text.length
  while (left < right) {
    const mid = Math.ceil((left + right) / 2)
    const candidate = `${text.slice(0, mid)}...`
    if (ctx.measureText(candidate).width <= width) {
      left = mid
    } else {
      right = mid - 1
    }
  }
  return `${text.slice(0, Math.max(1, left))}...`
}

function buildImagePDF(images: PdfImage[]): Uint8Array {
  const encoder = new TextEncoder()
  const chunks: Uint8Array[] = []
  const offsets: number[] = [0]
  let offset = 0
  const append = (chunk: Uint8Array | string) => {
    const bytes = typeof chunk === 'string' ? encoder.encode(chunk) : chunk
    chunks.push(bytes)
    offset += bytes.length
  }
  const addObject = (id: number, body: Array<Uint8Array | string>) => {
    offsets[id] = offset
    append(`${id} 0 obj\n`)
    body.forEach(append)
    append('\nendobj\n')
  }

  const totalObjects = 2 + images.length * 3
  append('%PDF-1.4\n% proxyai.best\n')
  addObject(1, ['<< /Type /Catalog /Pages 2 0 R >>'])

  const kids = images.map((_, index) => `${3 + index * 3} 0 R`).join(' ')
  addObject(2, [`<< /Type /Pages /Kids [${kids}] /Count ${images.length} >>`])

  images.forEach((image, index) => {
    const pageObject = 3 + index * 3
    const imageObject = pageObject + 1
    const contentObject = pageObject + 2
    const imageName = `Im${index + 1}`
    addObject(pageObject, [
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /${imageName} ${imageObject} 0 R >> >> /Contents ${contentObject} 0 R >>`
    ])
    addObject(imageObject, [
      `<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.data.length} >>\nstream\n`,
      image.data,
      '\nendstream'
    ])
    const content = `q\n595.28 0 0 841.89 0 0 cm\n/${imageName} Do\nQ`
    addObject(contentObject, [`<< /Length ${encoder.encode(content).length} >>\nstream\n${content}\nendstream`])
  })

  const xrefOffset = offset
  append(`xref\n0 ${totalObjects + 1}\n`)
  append('0000000000 65535 f \n')
  for (let id = 1; id <= totalObjects; id += 1) {
    append(`${String(offsets[id] || 0).padStart(10, '0')} 00000 n \n`)
  }
  append(`trailer\n<< /Size ${totalObjects + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`)

  const output = new Uint8Array(offset)
  let cursor = 0
  chunks.forEach((chunk) => {
    output.set(chunk, cursor)
    cursor += chunk.length
  })
  return output
}

function canvasToJpeg(canvas: HTMLCanvasElement): PdfImage {
  const dataURL = canvas.toDataURL('image/jpeg', 0.92)
  const base64 = dataURL.split(',')[1] || ''
  return {
    data: base64ToBytes(base64),
    width: canvas.width,
    height: canvas.height
  }
}

function base64ToBytes(base64: string): Uint8Array {
  const binary = atob(base64)
  const bytes = new Uint8Array(binary.length)
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index)
  }
  return bytes
}

function downloadBlob(bytes: Uint8Array, filename: string) {
  const copy = new Uint8Array(bytes.byteLength)
  copy.set(bytes)
  const blob = new Blob([copy.buffer], { type: 'application/pdf' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  document.body.appendChild(anchor)
  anchor.click()
  anchor.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function validationFallback(report: PurityReport): Array<{ name: string; status: PurityCheckStatus; message: string; score?: number; max_score?: number }> {
  return report.checks.slice(0, 6).map((check) => ({
    name: check.name,
    status: check.status,
    message: check.message,
    score: check.score,
    max_score: check.max_score
  }))
}

function wrapperSignalsForReport(report: PurityReport): string[] {
  return report.wrapper_signals?.length ? report.wrapper_signals : report.wrapperSignals || []
}

function scoreText(score: number | undefined, maxScore: number | undefined, labels: PdfLabels): string {
  if (typeof score === 'number' && typeof maxScore === 'number' && maxScore > 0) {
    return `${labels.scoreDetail}: ${score}/${maxScore}`
  }
  return ''
}


function verdictLabel(verdict: PurityVerdict, language: AppLanguage): string {
  const zh: Record<PurityVerdict, string> = {
    official_openai: '官方 OpenAI',
    openai_compatible: 'OpenAI 兼容',
    official_claude: '官方 Claude',
    claude_compatible: 'Claude 兼容',
    official_gemini: '官方 Gemini',
    gemini_compatible: 'Gemini 兼容',
    partial_compatible: '兼容受限',
    invalid_or_unavailable: '无效或不可用',
    unknown: '未知'
  }
  const en: Record<PurityVerdict, string> = {
    official_openai: 'Official OpenAI',
    openai_compatible: 'OpenAI compatible',
    official_claude: 'Official Claude',
    claude_compatible: 'Claude compatible',
    official_gemini: 'Official Gemini',
    gemini_compatible: 'Gemini compatible',
    partial_compatible: 'Compatibility limited',
    invalid_or_unavailable: 'Invalid or unavailable',
    unknown: 'Unknown'
  }
  return language === 'zh-CN' ? zh[verdict] : en[verdict]
}

function verdictTone(verdict: PurityVerdict): string {
  if (verdict === 'partial_compatible') {
    return '#d97706'
  }
  if (verdict === 'invalid_or_unavailable' || verdict === 'unknown') {
    return '#ff746c'
  }
  return '#68a8ff'
}

function statusLabel(status: PurityCheckStatus, language: AppLanguage): string {
  if (language !== 'zh-CN') {
    return status === 'pass' ? 'Pass' : status === 'warn' ? 'Warning' : 'Fail'
  }
  return status === 'pass' ? '通过' : status === 'warn' ? '警告' : '失败'
}

function statusColor(status: PurityCheckStatus): string {
  if (status === 'pass') {
    return '#68a8ff'
  }
  if (status === 'warn') {
    return '#e4b449'
  }
  return '#ff746c'
}

function providerLabel(provider: string): string {
  const normalized = normalizeTokenAuditProvider(provider)
  if (normalized === 'anthropic') {
    return 'Claude'
  }
  if (normalized === 'gemini') {
    return 'Gemini'
  }
  return 'OpenAI'
}

function formatDate(value: string, language: AppLanguage): string {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return value || '-'
  }
  return new Intl.DateTimeFormat(language, { dateStyle: 'medium', timeStyle: 'short' }).format(date)
}

function formatMS(value: number): string {
  return `${formatInteger(Math.max(0, Math.round(value)))}ms`
}

function formatInteger(value: number): string {
  return new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(value || 0)
}

function formatUSD(value: number): string {
  return `$${Number.isFinite(value) ? value.toFixed(4) : '0.0000'}`
}

function formatMultiplier(value: number): string {
  const safe = Number.isFinite(value) && value > 0 ? value : 0
  if (safe <= 0) return '-'
  return `${safe.toFixed(2).replace(/0+$/, '').replace(/\.$/, '')}x`
}

function formatPercent(value: number): string {
  if (!Number.isFinite(value)) {
    return '0%'
  }
  return `${Math.round(value > 1 ? value : value * 100)}%`
}

function pdfAuditToneColor(tone: TokenAuditTone): string {
  if (tone === 'good') return '#00df9a'
  if (tone === 'warn') return '#ffc857'
  if (tone === 'bad') return '#ff6673'
  return '#f4f2ff'
}

function auditInfoFill(tone: TokenAuditTone): string {
  if (tone === 'bad') return '#231018'
  if (tone === 'warn') return '#17121a'
  if (tone === 'good') return '#123421'
  return '#151422'
}

function auditInfoStroke(tone: TokenAuditTone): string {
  if (tone === 'bad') return '#6c2935'
  if (tone === 'warn') return '#5b461f'
  if (tone === 'good') return '#244b36'
  return '#242235'
}

function sampleRound(sample: PurityTokenAuditSample, fallbackIndex = 0): number {
  return sample.round || sample.index || fallbackIndex + 1
}

function safeFilePart(value: string): string {
  return String(value || 'report').replace(/[^a-z0-9._-]+/gi, '-').replace(/^-+|-+$/g, '').slice(0, 80) || 'report'
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, Math.round(value || 0)))
}
